version: 0.1
phases: 
  install:
    commands:
      - aws cloudformation package --template-file templates/samTemplate.yaml --s3-bucket aws-data-common --output-template-file outputSamTemplate.yaml
      - aws s3 cp templates/glueTemplate.yaml s3://aws-data-common/templates/glueTemplate.yaml

artifacts:
  type: zip
  files:
    - samTemplate.yaml
    - outputSamTemplate.yaml