version: 0.1
phases: 
  install:
    runtime-versions:
      python: 3.7
    commands:
      - aws cloudformation package --template-file samTemplate.yaml --s3-bucket aws-data-common --output-template-file outputSamTemplate.yaml
      - aws s3 cp templates/glueTemplate.yaml s3://aws-data-common/templates/glueTemplate.yaml
      - aws s3 cp templates/secretsTemplate.yaml s3://aws-data-common/templates/secretsTemplate.yaml
      - aws s3 cp codes/glue/* s3://aws-data-common/gluescripts/

artifacts:
  type: zip
  files:
    - samTemplate.yaml
    - outputSamTemplate.yaml