AWSTemplateFormatVersion: '2010-09-09'

Resources:
  CDDemoLambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: glueLambda
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      CodeUri: ./aws_lambda_codes/LambdaCode
      Description: 'Testing Lambda'
      MemorySize: 128
      Timeout: 30
      Role: 'arn:aws:iam::337769067848:role/LambdaFullAccess'
