AWSTemplateFormateVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Testing CICD Lmabda
Resources:
  CDDemoLambda:
    Type: 'AWS::Serverless::Function'
    Properties:
    Handler: lambda_function.lambda_handler
    Runtime: python3.6
    CodeUri: ./LambdaCode
    Description: 'Testing Lambda'
    MemorySize: 128
    Timeout: 30
    Role: 'arn:aws:iam::337769067848:role/LambdaFullAccess'