AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Testing CICD Lmabda

Parameters:
  LambdaFullAccessRole:
    Type: String
    Description: Lambda Full access Role
    Default: arn:aws:iam::337769067848:role/LambdaFullAccess
  TargetS3Bucket:
    Type: String
    Description: Target S3 Bucket
    Default: aws-data-common
  DBSecretID:
    Type: String
    Description: DB secret ID
    Default: db-secrets-recursive-lambda

  RecursiveLambdaScheduleExpression: 
    Description: schedule expression for Recursive Lambda
    Type: String
    Default: rate(1 day) 

Resources:
  PythonLibrariesLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      CompatibleRuntimes:
        - python3.8
      ContentUri: ./codes/aws_lambda_codes/LambdaLib
      Description: Reusable library functions and configuration
      LayerName: python_lambda_libraries
      RetentionPolicy: Retain

  RecursiveLambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: recursive_lambda.lambda_handler
      Runtime: python3.8
      CodeUri: ./codes/aws_lambda_codes/recursiveLambda
      Description: 'Recursive lambda for extracting the data'
      MemorySize: 128
      Timeout: 30
      Environment:
        Variables:
          targetS3Bucket: !Ref TargetS3Bucket
          DBsecret: !Ref DBSecretID
          TargetLoc: recursive_lambdatgt/
      Layers: 
        - !Ref PythonLibrariesLayer
      Role: !Ref LambdaFullAccessRole

  RecursiveLambdaScheduleTrigger:
    Type: AWS::Events::Rule
    Properties: 
      Description: Daily event that triggers recursive lambda function 
      ScheduleExpression: !Ref RecursiveLambdaScheduleExpression
      State: ENABLED
      Targets: 
        - Arn: !GetAtt RecursiveLambda.Arn
          Id: RecursiveScheduleEventRule

  RecursiveLambdaInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref RecursiveLambda
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt RecursiveLambdaScheduleTrigger.Arn


  CDDemoLambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      CodeUri: ./codes/aws_lambda_codes/LambdaCode
      Description: 'Testing Lambda'
      MemorySize: 128
      Timeout: 30
      Role: 'arn:aws:iam::337769067848:role/LambdaFullAccess'

  TaskMangerServiceLambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      CodeUri: ./codes/aws_lambda_codes/taskmanagerserv
      Description: 'API taskmanagerserv Lambda'
      MemorySize: 128
      Timeout: 300
      Role: !Ref LambdaFullAccessRole

  TestLambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: recursive_lambda.lambda_handler
      Runtime: python3.7
      CodeUri: ./codes/aws_lambda_codes/testlambda
      Description: 'Recursive lambda for extracting the data'
      MemorySize: 128
      Timeout: 30
      Environment:
        Variables:
          targetS3Bucket: !Ref TargetS3Bucket
          DBsecret: !Ref DBSecretID
          TargetLoc: recursive_lambdatgt/
      Layers: 
        - !Ref PythonLibrariesLayer
      Role: !Ref LambdaFullAccessRole

  GlueStack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: https://aws-data-common.s3.ap-south-1.amazonaws.com/templates/glueTemplate.yaml
      TimeoutInMinutes: 60

  SecretsStack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: https://aws-data-common.s3.ap-south-1.amazonaws.com/templates/secretsTemplate.yaml
      TimeoutInMinutes: 60
