AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Testing CICD Lmabda
Resources:
  CDDemoLambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      CodeUri: ./codes/aws_lambda_codes/LambdaCode
      Description: 'Testing Lambda'
      MemorySize: 128
      Timeout: 30
      Role: 'arn:aws:iam::337769067848:role/LambdaFullAccess'

  GlueStack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: https://aws-data-common.s3.ap-south-1.amazonaws.com/templates/glueTemplate.yaml
      TimeoutInMinutes: 60
