AWSTemplateFormatVersion: '2010-09-09'

Resources:
  DBCredsSM:
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Name: db-secrets-recursive-lambda
      Description: This secret has DB connection which need to feed manually
      SecretString: '{"username":"test","password":"test"}'
