AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  LambdaFullAccessRole:
    Type: String
    Description: Lambda Full access Role
    Default: arn:aws:iam::337769067848:role/LambdaFullAccess
  TargetS3Bucket:
    Type: String
    Description: Target S3 Bucket
    Default: aws-data-common
  DBSecretID:
    Type: String
    Description: DB secret ID
    Default: db-secrets-recursive-lambda
 
Resources:
  DataStream:
    Type: AWS::Kinesis::Stream
    Properties: 
      Name: String
      RetentionPeriodHours: Integer
      ShardCount: Integer
      StreamEncryption: 
        StreamEncryption
      Tags: 
        - Tag